apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    deploy: front
  name: front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: front
    spec:
      containers:
      - image: err0r500/demok8s-front
        name: demok8s-front
        resources: {}
        env:
        - name: REDIS 
          valueFrom:
            secretKeyRef:
              name: db
              key: redis
